# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/streamgpt',
                'doc_host': 'https://TesfaAsmara.github.io',
                'git_url': 'https://github.com/TesfaAsmara/streamgpt',
                'lib_path': 'streamgpt'},
  'syms': {}}
